import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackgroundShapes from "@/components/BackgroundShapes";

import { Plus_Jakarta_Sans } from "next/font/google";
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${jakarta.className} antialiased`}>
        <div className="w-screen h-screen overflow-hidden relative select-none">
          <BackgroundShapes />
          {children}
        </div>
      </body>
    </html>
  );
}
